matrix:
  include:
    - os: linux
      sudo: false
      language: python
      python: "2.7"
    - os: linux
      sudo: false
      language: python
      python: "3.2"
    - os: osx
      osx_image: xcode7.3
      language: generic
      env: TRAVIS_PYTHON_VERSION="2" BREW_DEPS="python"
    - os: osx
      osx_image: xcode7.3
      language: generic
      env: TRAVIS_PYTHON_VERSION="3" BREW_DEPS="python3"

addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.9
   - g++-4.9

script:
  - CXX=g++-4.9 ./waf configure
  - ./waf