os: linux
sudo: false
language: python

env:
  - CXX=g++
  - CXX=clang++
python:
  - "2.7"
  - "3.4"

cache:
  directories:
    - llvm-3.8.0

addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.9
   - g++-4.9

script:
  -
    if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      export LLVM_VERSION=3.8.0;
      if [ -z "$(ls -A llvm-$LLVM_VERSION)" ]; then
        wget -O llvm-$LLVM_VERSION.tar.xz http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz;
        mkdir llvm-$LLVM_VERSION;
        xzcat llvm-$LLVM_VERSION.tar.xz | tar -xvf - --strip 1 -C llvm-$LLVM_VERSION;
      fi;
      llvm-$LLVM_VERSION/bin/llvm-config --version;
      export LLVM_CONFIG="llvm-$LLVM_VERSION/bin/llvm-config";
    fi;
    export LD_LIBRARY_PATH=$HOME/llvm-$LLVM_VERSION/lib:$LD_LIBRARY_PATH
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; export CC="gcc-4.9"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX=$HOME/llvm-$LLVM_VERSION/bin/clang++; export CC=$HOME/llvm-$LLVM_VERSION/bin/clang; fi
  - ls -lah $HOME
  - ls -lah $HOME/llvm-$LLVM_VERSION
  - ls -lah $HOME/llvm-$LLVM_VERSION/bin
  - mkdir build
  - cd build
  - cmake ..
  - make

after_failure:
  - cat build/config.log
