os: linux
sudo: false
language: python

env:
  - CXX=g++
  - CXX=clang++
python:
  - "2.7"
  - "3.4"


addons:
 apt:
   sources:
   - llvm-toolchain-precise-3.6
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.9
   - g++-4.9
   - clang-3.6

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Replace dep1 dep2 ... with your dependencies
  - conda create -c ilastik -q -n test-environment python=$TRAVIS_PYTHON_VERSION vigra && source activate test-environment || true

script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
  - ./waf configure -j1
  - ./waf -j1
  - ./waf test

after_failure:
  - cat build/config.log
