matrix:
  include:
    - os: linux
      sudo: false
      language: python
      python: "2.7"
    - os: linux
      sudo: false
      language: python
      python: "3.2"

addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.9
   - g++-4.9

script:
  - CXX=g++-4.9 ./waf configure
  - ./waf

after_failure:
  - cat build/config.log