package:
  name: fastfilters
  version: "0.1"

source:
  git_url: https://github.com/svenpeter42/fastfilters
  git_tag: v0.1

build:
  {% set build_num = 1 %}
  number: {{ build_num }}
  string: py{{CONDA_PY}}_{{build_num}}_g{{GIT_FULL_HASH[:7]}}

requirements:
  build:
    - gcc 4.8.5 # [linux]
    - gcc 4.8.5 # [osx]
    - python 2.7*|3.5*
    - python {{PY_VER}}*

  run:
    - python {{PY_VER}}*